/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\lib\astryx-theme.ts
 * Command: astryx theme build src\lib\astryx-theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/// <reference path="./ssw.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const sswTheme: DefinedTheme;
