steps:
  # 1. Build the image, tagged with the git tag that triggered this build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kyn3n-ssw-ticketing-buyerform-2026/ssw-ticketing-2026-public-form:$TAG_NAME'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=$_API_BASE_URL'
      - '-f'
      - 'Dockerfile'
      - '.'

  # 2. Push the image into the cloud's own docker registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kyn3n-ssw-ticketing-buyerform-2026/ssw-ticketing-2026-public-form:$TAG_NAME'
    waitFor: ['build']

  # 3. Deploy the frontend to Cloud Run
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ssw-ticketing-2026-public-form'
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kyn3n-ssw-ticketing-buyerform-2026/ssw-ticketing-2026-public-form:$TAG_NAME'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated'
    waitFor: ['push']

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kyn3n-ssw-ticketing-buyerform-2026/ssw-ticketing-2026-public-form:$TAG_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
