import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run theme:build` — edit src/lib/astryx-theme.ts instead.
    "src/lib/ssw.js",
    "src/lib/ssw.d.ts",
    "src/lib/ssw.variants.d.ts",
  ]),
]);

export default eslintConfig;
